# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f644c73b49e6450f7ad3ac7e69c011259d70695b64ece3a35d3949b3faa60fc35e45cd66e0e949de940ad37b59b7b583364a35120ccf52451a76e4600ab7ea7

test:
  secret_key_base: 42d1e86a15ee0a60cd537731ab30bacd39f3f07e82b5c290e2d3c27f3d6617c57a27fcdcd993473955dfd197f2d2c7e5bfcecce7ba50d3c17b4fe6f23d979804

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
